export const columnHeaderMapping = {
  SEASON_YEAR: "SEASON",
  LEAGUE: "LEAGUE",
  DIV: "DIVISION",
  SEASON_TYPE: "SEASON TYPE",
  TEAM: "TEAM",
  PLAYER: "PLAYER",
  POS: "POSITION",
  ROLE: "OFFENSIVE ROLE",
  ID: "ID",
  EST_POS: "Estimated Position",
  EST_ROLE: "Estimated Offensive Role",
  BORN: "BORN",
  GP: "GP",
  MP: "MP",
  PT: "PT",
  RB: "RB",
  AS: "AS",
  ST: "ST",
  BS: "BS",
  TO: "TO",
  PF: "PF",
  EF: "EF",
  DD: "DD",
  TD: "TD",
  MPG: "MP",
  PPG: "PT",
  RPG: "RB",
  APG: "AS",
  SPG: "ST",
  BPG: "BS",
  TOPG: "TO",
  PFPG: "PF",
  EFPG: "EF",
  PER: "PER",
  PIE: "PIE",
  "2PM": "2PM",
  "2PA": "2PA",
  "2P%": "2P%",
  "3PM": "3PM",
  "3PA": "3PA",
  "3P%": "3P%",
  FGM: "FGM",
  FGA: "FGA",
  "FG%": "FG%",
  FTM: "FTM",
  FTA: "FTA",
  "FT%": "FT%",
  ORTG: "ORTG",
  DRTG: "DRTG",
  NRTG: "NRTG",
  OBPM: "OBPM",
  DBPM: "DBPM",
  BPM: "BPM",
  VORP: "VORP",
  OWS: "OWS",
  DWS: "DWS",
  WS: "WS",
  WS_40: "WS/40",
  FIC: "FIC",
  FIC_Gm: "FIC/Gm",
  AS_RATIO: "ASR",
  AS_RATE: "ASRA",
  AS_TO: "AS/TO",
  "REB%": "REB%",
  "ST%": "ST%",
  "BS%": "BS%",
  USAGE: "USG%",
  "TS%": "TS%",
  "EFG%": "EFG%",
  "TOV%": "TOV%",
  "ORB%": "ORB%",
  FT_RATE: "FTR",
  TEAM_Short: "TEAM",
  TEAM_ID: "TEAM",
  DR: "DR",
  OR: "OR",
  OPP_PPG: "PT",
  OPP_RPG: "RB",
  OPP_APG: "AS",
  OPP_SPG: "ST",
  OPP_BPG: "BS",
  "OPP_2P%": "2P%",
  "OPP_3P%": "3P%",
  "OPP_FG%": "FG%",
  "OPP_FT%": "FT%",
  WINS: "WINS",
  PACE: "PACE",
  PPP: "PPP",
  "OPP_EFG%": "EFG%",
  "OPP_TOV%": "TOV%",
  "OPP_ORB%": "ORB%",
  "OPP_FT_RATE": "FTR",
  "ORPG": "OR",
  "DRPG": "DR",
  "Team": "TEAM",
  "Win%": "WIN%",
  'ORTG_ADJ': "ORTG",
  'DRTG_ADJ': "DRTG",
  'NRTG_ADJ': "NRTG",
  'STOPS_Gm': "ST/Gm",
  '2PMPG': "2PM",
  '2PAPG': "2PA",
  '3PMPG': "3PM",
  '3PAPG': "3PA",
  'FGMPG': "FGM",
  'FGAPG': "FGA",
  'FTMPG': "FTM",
  'FTAPG': "FTA",
  'OPP3PR': "3PR",
};

export const ToolheadersMapping = {
  SEASON_YEAR: "Season",
  LEAGUE: "League",
  DIV: "Division",
  SEASON_TYPE: "Season Type",
  TEAM: "Team",
  PLAYER: "Player",
  POS: "Position",
  ROLE: "Offensive Role",
  ID: "ID",
  EST_POS: "Estimated Position",
  EST_ROLE: "Estimated Offensive Role",
  BORN: "Year of Birth",
  GP: "Games Played",
  MP: "Minutes Played",
  PT: "Points",
  RB: "Rebounds",
  AS: "Assists",
  ST: "Steals",
  BS: "Blocked Shots",
  TO: "Turnovers",
  PF: "Personal Fouls",
  EF: "Efficiency",
  DD: "Double Doubles",
  TD: "Triple Doubles",
  MPG: "Minutes per Game",
  PPG: "Points per Game",
  RPG: "Rebounds per Game",
  APG: "Assists per Game",
  SPG: "Steals per Game",
  BPG: "Blocked Shots per Game",
  TOPG: "Turnovers per Game",
  PFPG: "Personal Fouls per Game",
  EFPG: "Efficiency per Game",
  PER: "Player Efficiency Rating",
  PIE: "Player Impact Estimate",
  "2PM": "2-Pointer Made",
  "2PA": "2-Point Attempts",
  "2P%": "2-Point Percentage",
  "3PM": "3-Pointer Made",
  "3PA": "3-Point Attempts",
  "3P%": "3-Point Percentage",
  FGM: "Field Goals Made",
  FGA: "Field Goal Attempts",
  "FG%": "Field Goal Percentage",
  FTM: "Free Throws Made",
  FTA: "Free Throw Attempts",
  "FT%": "Free Throw Percentage",
  ORTG: "Offensive Rating",
  DRTG: "Defensive Rating",
  NRTG: "Net Rating",
  OBPM: "Offensive Boxscore Plus-Minus",
  DBPM: "Defensive Boxscore Plus-Minus",
  BPM: "Boxscore Plus-Minus",
  VORP: "Value over Replacement Player",
  OWS: "Offensive Win Shares",
  DWS: "Defensive Win Shares",
  WS: "Win Shares",
  WS_40: "Win Shares per 40 Minutes",
  FIC: "Floor Impact Counter",
  FIC_Gm: "Floor Impact Counter per Game",
  AS_RATIO: "Assist Ratio - Assists per 100 Possessions",
  AS_RATE: "Assist Rate - Passing Tendency (High Value = High Passing Tendency)",
  AS_TO: "Assist to Turnover Ratio",
  "REB%": "Rebound Percentage",
  "ST%": "Steal Percentage",
  "BS%": "Block Percentage",
  USAGE: "Usage Rate",
  "TS%": "True Shooting Percentage",
  "EFG%": "Effective Field Goal Percentage",
  "TOV%": "Turnover Percentage",
  "ORB%": "Offensive Rebound Percentage",
  FT_RATE: "Free Throw Rate",
  TEAM_Short: "Team",
  TEAM_ID: "Team",
  DR: "Defensive Rebounds",
  OR: "Offensive Rebounds",
  OPP_PPG: "Opponent Points per Game",
  OPP_RPG: "Opponent Rebounds per Game",
  OPP_APG: "Opponent Assists per Game",
  OPP_SPG: "Opponent Steals per Game",
  OPP_BPG: "Opponent Blocks per Game",
  "OPP_2P%": "Opponent 2-Point Percentage",
  "OPP_3P%": "Opponent 3-Point Percentage",
  "OPP_FG%": "Opponent Field Goal Percentage",
  "OPP_FT%": "Opponent Free Throw Percentage",
  WINS: "Wins",
  PACE: "Team Pace - Possessions per Game",
  PPP: "Points per Possession",
  "OPP_EFG%": "Opponent Effective Field Goal Percentage",
  "OPP_TOV%": "Opponent Turnover Percentage",
  "OPP_ORB%": "Opponent Offensive Rebound Percentage",
  "OPP_FT_RATE": "Opponent Free Throw Rate",
  "ORPG": "Offensive Rebounds per Game",
  "DRPG": "Defensive Rebounds per Game",
  "Win%": "Win Percentage",
  'ORTG_ADJ': "Pace adjusted Offensive Rating",
  'DRTG_ADJ': "Pace adjusted Defensive Rating",
  'NRTG_ADJ': "Pace adjusted Net Rating",
  'STOPS_Gm': "Stops per Game",
  '2PMPG': "2-Pointer Made",
  '2PAPG': "2-Point Attempts",
  '3PMPG': "3-Pointer Made",
  '3PAPG': "3-Point Attempts",
  'FGMPG': "Field Goals Made",
  'FGAPG': "Field Goal Attempts",
  'FTMPG': "Free Throws Made",
  'FTAPG': "Free Throw Attempts",
  'DFG%': "Defensive Field Goal Percentage",
  'DRB%': "Defensive Rebound Percentage",
  'STOP%': "Stop Percentage",
  'OPP3PR': "Opponent 3-Point Attempt Rate",
  '3PR': "3-Point Attempt Rate",
};

export const teamImageMappings = {
  'Alba Berlin': '/src/images/NBBL1.jpg',
  'ART Giants Düsseldorf': '/src/images/NBBL2.jpg',
  'Bamberg freakcity academy': '/src/images/img41.jpg',
  'Baskets Juniors Oldenburg': '/src/images/img15.jpg',
  'Baskets Paderborn': '/src/images/img4.jpg',
  'Bayer Giants Leverkusen': '/src/images/img7.jpg',
  'Berlin Braves Baskets': '/src/images/img5.jpg',
  'Basketball Löwen Erfurt': '/src/images/img41.jpg',
  'BBA Giants Kornwestheim': '/src/images/img41.jpg',
  'BBA Hagen': '/src/images/img41.jpg',
  'Dresden Titans': '/src/images/img41.jpg',
  'Eintracht Frankfurt': '/src/images/img3.jpg',
  'Eisbären Bremerhaven': '/src/images/img41.jpg',
  'FC Bayern München': '/src/images/img14.jpg',
  'Hamburg Towers': '/src/images/img41.jpg',
  'HAKRO Merlins Crailsheim': '/src/images/img41.jpg',
  'KICKZ IBAM': '/src/images/img12.jpg',
  'Medipolis SC Jena': '/src/images/img16.jpg',
  'Metropol Baskets Ruhr': '/src/images/img41.jpg',
  'Mitteldeutsche Basketball Academy': '/src/images/img41.jpg',
  'Niners Chemnitz Academy': '/src/images/img8.jpg',
  'Orange Academy': '/src/images/img41.jpg',
  'Phoenix Hagen': '/src/images/img41.jpg',
  'Porsche BBA Ludwigsburg': '/src/images/img9.jpg',
  'ROTH Energie BBA Giessen 46ers': '/src/images/img41.jpg',
  'ratiopharm Ulm': '/src/images/img41.jpg',
  'RheinStars Köln': '/src/images/img41.jpg',
  'Rostock Seawolves': '/src/images/img41.jpg',
  'Sartorius Juniors': '/src/images/img1.jpg',
  'SG Junior Löwen Braunschweig': '/src/images/img41.jpg',
  'Team Bonn/Rhöndorf': '/src/images/img41.jpg',
  'Team Südhessen': '/src/images/img41.jpg',
  'Team Urspring': '/src/images/img10.jpg',
  'TG Hanau': '/src/images/img41.jpg',
  'Tornados Franken': '/src/images/img13.jpg',
  'TS Jahn München': '/src/images/img41.jpg',
  'UBC Münster': '/src/images/img2.jpg',
  'USC Heidelberg': '/src/images/img41.jpg',
  'VfL Kirchheim Knights': '/src/images/img41.jpg',
  'Würzburg Baskets Akademie': '/src/images/img41.jpg',
  'Young Gladiators Trier': '/src/images/img41.jpg',
  'Young Rasta Dragons': '/src/images/img11.jpg',
};

export default teamImageMappings;

