import img100 from '../images/img100.png';
import img101 from '../images/img101.png';
import img102 from '../images/img102.png';
import img103 from '../images/img103.png';
import img104 from '../images/img104.png';
import img105 from '../images/img105.png';
import img106 from '../images/img106.png';
import img107 from '../images/img107.png';
import img108 from '../images/img108.png';
import img109 from '../images/img109.png';
import img110 from '../images/img110.png';
import img111 from '../images/img111.png';
import img112 from '../images/img112.png';
import img113 from '../images/img113.png';
import img114 from '../images/img114.png';
import img115 from '../images/img115.png';
import img116 from '../images/img116.png';
import img117 from '../images/img117.png';
import img118 from '../images/img118.png';
import img119 from '../images/img119.png';
import img120 from '../images/img120.png';
import img121 from '../images/img121.png';
import img122 from '../images/img122.png';
import img123 from '../images/img123.png';
import img124 from '../images/img124.png';
import img125 from '../images/img125.png';
import img126 from '../images/img126.png';
import img127 from '../images/img127.png';
import img128 from '../images/img128.png';
import img129 from '../images/img129.png';
import img130 from '../images/img130.png';
import img131 from '../images/img131.png';
import img132 from '../images/img132.png';
import img133 from '../images/img133.png';
import img134 from '../images/img134.png';
import img135 from '../images/img135.png';
import img136 from '../images/img136.png';
import img137 from '../images/img137.png';
import img138 from '../images/img138.png';
import img139 from '../images/img139.png';
import img140 from '../images/img140.png';
import img141 from '../images/img141.png';
import img142 from '../images/img142.png';
import img143 from '../images/img143.png';
import img144 from '../images/img144.png';
import img145 from '../images/img145.png';
import img146 from '../images/img146.png';
import img147 from '../images/img147.png';
import img148 from '../images/img148.png';
import img149 from '../images/img149.png';
import img150 from '../images/img150.png';
import img151 from '../images/img151.png';
import img152 from '../images/img152.png';
import img153 from '../images/img153.png';
import img154 from '../images/img154.png';
import img155 from '../images/img155.png';
import img156 from '../images/img156.png';
import img157 from '../images/img157.png';
import img158 from '../images/img158.png';
import img159 from '../images/img159.png';
import img160 from '../images/img160.png';

export const columnHeaderMapping = {
  SEASON_YEAR: "SEASON",
  LEAGUE: "LEAGUE",
  DIV: "DIVISION",
  SEASON_TYPE: "SEASON TYPE",
  TEAM: "TEAM",
  PLAYER: "PLAYER",
  POS: "POSITION",
  ROLE: "OFFENSIVE ROLE",
  ID: "ID",
  EST_POS: "Estimated Position",
  EST_ROLE: "Estimated Offensive Role",
  BORN: "BORN",
  GP: "GP",
  MP: "MP",
  PT: "PT",
  RB: "RB",
  AS: "AS",
  ST: "ST",
  BS: "BS",
  TO: "TO",
  PF: "PF",
  EF: "EF",
  DD: "DD",
  TD: "TD",
  MPG: "MP",
  PPG: "PT",
  RPG: "RB",
  APG: "AS",
  SPG: "ST",
  BPG: "BS",
  TOPG: "TO",
  PFPG: "PF",
  EFPG: "EF",
  PER: "PER",
  PIE: "PIE",
  "2PM": "2PM",
  "2PA": "2PA",
  "2P%": "2P%",
  "3PM": "3PM",
  "3PA": "3PA",
  "3P%": "3P%",
  FGM: "FGM",
  FGA: "FGA",
  "FG%": "FG%",
  FTM: "FTM",
  FTA: "FTA",
  "FT%": "FT%",
  ORTG: "ORTG",
  DRTG: "DRTG",
  NRTG: "NRTG",
  OBPM: "OBPM",
  DBPM: "DBPM",
  BPM: "BPM",
  VORP: "VORP",
  OWS: "OWS",
  DWS: "DWS",
  WS: "WS",
  WS_40: "WS/40",
  FIC: "FIC",
  FIC_Gm: "FIC/Gm",
  AS_RATIO: "ASR",
  AS_RATE: "ASRA",
  AS_TO: "AS/TO",
  "REB%": "REB%",
  "ST%": "ST%",
  "BS%": "BS%",
  USAGE: "USG%",
  "TS%": "TS%",
  "EFG%": "EFG%",
  "TOV%": "TOV%",
  "ORB%": "ORB%",
  FT_RATE: "FTR",
  TEAM_Short: "TEAM",
  TEAM_ID: "TEAM",
  DR: "DR",
  OR: "OR",
  OPP_PPG: "PT",
  OPP_RPG: "RB",
  OPP_APG: "AS",
  OPP_SPG: "ST",
  OPP_BPG: "BS",
  "OPP_2P%": "2P%",
  "OPP_3P%": "3P%",
  "OPP_FG%": "FG%",
  "OPP_FT%": "FT%",
  WINS: "WINS",
  PACE: "PACE",
  PPP: "PPP",
  "OPP_EFG%": "EFG%",
  "OPP_TOV%": "TOV%",
  "OPP_ORB%": "ORB%",
  "OPP_FT_RATE": "FTR",
  "ORPG": "OR",
  "DRPG": "DR",
  "Team": "TEAM",
  "Win%": "WIN%",
  'ORTG_ADJ': "ORTG",
  'DRTG_ADJ': "DRTG",
  'NRTG_ADJ': "NRTG",
  'STOPS_Gm': "St/Gm",
  '2PMPG': "2PM",
  '2PAPG': "2PA",
  '3PMPG': "3PM",
  '3PAPG': "3PA",
  'FGMPG': "FGM",
  'FGAPG': "FGA",
  'FTMPG': "FTM",
  'FTAPG': "FTA",
  'OPP3PR': "3PR",
  HIGHPT: "PT",
  HIGHAS: "AS",
  HIGHRB: "RB",
  HIGHST: "ST",
  HIGHBS: "BS",
  Pt_TSA: "PT/TSA",
  PT36: "PT",
  OR36: "OR",
  DR36: "DR",
  RB36: "RB",
  AS36: "AS",
  ST36: "ST",
  BS36: "BS",
  TO36: "TO",
  PF36: "PF",
  EF36: "EF",
  PTMIN: "PT",
  ORMIN: "OR",
  DRMIN: "DR",
  RBMIN: "RB",
  ASMIN: "AS",
  STMIN: "ST",
  BSMIN: "BS",
  TOMIN: "TO",
  PFMIN: "PF",
  EFMIN: "EF",
  PTPER: "PT",
  ORPER: "OR",
  DRPER: "DR",
  RBPER: "RB",
  ASPER: "AS",
  STPER: "ST",
  BSPER: "BS",
  TOPER: "TO",
  PFPER: "PF",
  EFPER: "EF",
};

export const ToolheadersMapping = {
  SEASON_YEAR: "Season",
  LEAGUE: "League",
  DIV: "Division",
  SEASON_TYPE: "Season Type",
  TEAM: "Team",
  PLAYER: "Player",
  POS: "Position",
  ROLE: "Offensive Role",
  ID: "ID",
  EST_POS: "Estimated Position",
  EST_ROLE: "Estimated Offensive Role",
  BORN: "Year of Birth",
  GP: "Games Played",
  MP: "Minutes Played",
  PT: "Points",
  RB: "Rebounds",
  AS: "Assists",
  ST: "Steals",
  BS: "Blocked Shots",
  TO: "Turnovers",
  PF: "Personal Fouls",
  EF: "Efficiency",
  DD: "Double Doubles",
  TD: "Triple Doubles",
  MPG: "Minutes per Game",
  PPG: "Points per Game",
  RPG: "Rebounds per Game",
  APG: "Assists per Game",
  SPG: "Steals per Game",
  BPG: "Blocked Shots per Game",
  TOPG: "Turnovers per Game",
  PFPG: "Personal Fouls per Game",
  EFPG: "Efficiency per Game",
  PER: "Player Efficiency Rating",
  PIE: "Player Impact Estimate",
  "2PM": "2-Pointer Made",
  "2PA": "2-Point Attempts",
  "2P%": "2-Point Percentage",
  "3PM": "3-Pointer Made",
  "3PA": "3-Point Attempts",
  "3P%": "3-Point Percentage",
  FGM: "Field Goals Made",
  FGA: "Field Goal Attempts",
  "FG%": "Field Goal Percentage",
  FTM: "Free Throws Made",
  FTA: "Free Throw Attempts",
  "FT%": "Free Throw Percentage",
  ORTG: "Offensive Rating",
  DRTG: "Defensive Rating",
  NRTG: "Net Rating",
  OBPM: "Offensive Boxscore Plus-Minus",
  DBPM: "Defensive Boxscore Plus-Minus",
  BPM: "Boxscore Plus-Minus",
  VORP: "Value over Replacement Player",
  OWS: "Offensive Win Shares",
  DWS: "Defensive Win Shares",
  WS: "Win Shares",
  WS_40: "Win Shares per 40 Minutes",
  FIC: "Floor Impact Counter",
  FIC_Gm: "Floor Impact Counter per Game",
  AS_RATIO: "Assist Ratio - Assists per 100 Possessions",
  AS_RATE: "Assist Rate - Passing Tendency (High Value = High Passing Tendency)",
  AS_TO: "Assist to Turnover Ratio",
  "REB%": "Rebound Percentage",
  "ST%": "Steal Percentage",
  "BS%": "Block Percentage",
  USAGE: "Usage Rate",
  "TS%": "True Shooting Percentage",
  "EFG%": "Effective Field Goal Percentage",
  "TOV%": "Turnover Percentage",
  "ORB%": "Offensive Rebound Percentage",
  FT_RATE: "Free Throw Rate",
  TEAM_Short: "Team",
  TEAM_ID: "Team",
  DR: "Defensive Rebounds",
  OR: "Offensive Rebounds",
  OPP_PPG: "Opponent Points per Game",
  OPP_RPG: "Opponent Rebounds per Game",
  OPP_APG: "Opponent Assists per Game",
  OPP_SPG: "Opponent Steals per Game",
  OPP_BPG: "Opponent Blocks per Game",
  "OPP_2P%": "Opponent 2-Point Percentage",
  "OPP_3P%": "Opponent 3-Point Percentage",
  "OPP_FG%": "Opponent Field Goal Percentage",
  "OPP_FT%": "Opponent Free Throw Percentage",
  WINS: "Wins",
  PACE: "Team Pace - Possessions per Game",
  PPP: "Points per Possession",
  "OPP_EFG%": "Opponent Effective Field Goal Percentage",
  "OPP_TOV%": "Opponent Turnover Percentage",
  "OPP_ORB%": "Opponent Offensive Rebound Percentage",
  "OPP_FT_RATE": "Opponent Free Throw Rate",
  "ORPG": "Offensive Rebounds per Game",
  "DRPG": "Defensive Rebounds per Game",
  "Win%": "Win Percentage",
  'ORTG_ADJ': "Pace adjusted Offensive Rating",
  'DRTG_ADJ': "Pace adjusted Defensive Rating",
  'NRTG_ADJ': "Pace adjusted Net Rating",
  'STOPS_Gm': "Stops per Game",
  '2PMPG': "2-Pointer Made per Game",
  '2PAPG': "2-Point Attempts per Game",
  '3PMPG': "3-Pointer Made per Game",
  '3PAPG': "3-Point Attempts per Game",
  'FGMPG': "Field Goals Made per Game",
  'FGAPG': "Field Goal Attempts per Game",
  'FTMPG': "Free Throws Made per Game",
  'FTAPG': "Free Throw Attempts per Game",
  'DFG%': "Defensive Field Goal Percentage",
  'DRB%': "Defensive Rebound Percentage",
  'STOP%': "Stop Percentage",
  'OPP3PR': "Opponent 3-Point Attempt Rate",
  '3PR': "3-Point Attempt Rate",
  'FLOOR%': "Decision Making - (High Value = Good Decision Making)",
  HIGHPT: "Season High Points",
  HIGHAS: "Season High Assists",
  HIGHRB: "Season High Rebounds",
  HIGHST: "Season High Steals",
  HIGHBS: "Season High Blocks",
  '20+': "20+ Points Games",
  '30+': "30+ Points Games",
  '40+': "40+ Points Games",
  Pt_TSA: "Points per True Shooting Attempt",
  PT36: "Points per 36 Minutes",
  OR36: "Offensive Rebounds per 36 Minutes",
  DR36: "Defensive Rebounds per 36 Minutes",
  RB36: "Rebounds per 36 Minutes",
  AS36: "Assists per 36 Minutes",
  ST36: "Steals per 36 Minutes",
  BS36: "Blocks per 36 Minutes",
  TO36: "Turnovers per 36 Minutes",
  PF36: "Personal Fouls per 36 Minutes",
  EF36: "Efficiency per 36 Minutes",
  PTMIN: "Points per Minute",
  ORMIN: "Offensive Rebounds per Minute",
  DRMIN: "Defensive Rebounds per Minute",
  RBMIN: "Rebounds per Minute",
  ASMIN: "Assists per Minute",
  STMIN: "Steals per Minute",
  BSMIN: "Blocks per Minute",
  TOMIN: "Turnovers per Minute",
  PFMIN: "Personal Fouls per Minute",
  EFMIN: "Efficiency per Minute",
  PTPER: "Minutes per Point",
  ORPER: "Minutes per Offensive Rebound",
  DRPER: "Minutes per Defensive Rebound",
  RBPER: "Minutes per Rebound",
  ASPER: "Minutes per Assist",
  STPER: "Minutes per Steal",
  BSPER: "Minutes per Block",
  TOPER: "Minutes per Turnover",
  PFPER: "Minutes per Personal Foul",
  EFPER: "Minutes per Efficiency",
};

export const teamImageMappings = {
  'Jahn München': img100,
  Leverkusen: img101,
  Oldenburg: img102,
  Paderborn: img103,
  'Phoenix Hagen': img104,
  'Bonn-Rhöndorf': img105,
  Köln: img106,
  Vechta: img107,
  'Alba Berlin': img108,
  'Berlin Braves': img109,
  Göttingen: img110,
  Giessen: img111,
  Frankfurt: img112,
  Bamberg: img113,
  Jena: img114,
  Ulm: img115,
  'FC Bayern': img116,
  Ludwigsburg: img117,
  Urspring: img118,
  Hamburg: img119,
  Düsseldorf: img120,
  IBAM: img121,
  Chemnitz: img122,
  'Rasta Academy': img123,
  Hanau: img124,
  Orange: img125,
  'BBA Hagen': img126,
  Bremerhaven: img127,
  'Rhein-Neckar': img128,
  Metropol: img129,
  Würzburg: img130,
  Bayreuth: img131,
  Münster: img132,
  Rostock: img133,
  Heidelberg: img134,
  Dresden: img135,
  Braunschweig: img136,
  Erfurt: img137,
  Südhessen: img138,
  Nürnberg: img139,
  Kirchheim: img140,
  Potsdam: img141,
  MBA: img142,
  Tübingen: img143,
  Karlsruhe: img144,
  Lichterfelde: img145,
  'Young Bulls': img146,
  Rockets: img147,
  Bramfeld: img148,
  Friedenau: img149,
  Oberpfalz: img150,
  Zehlendorf: img151,
  'SG Bernau': img152,
  'Team Frankfurt': img153,
  ALBASS: img154,
  'München-Ost': img155,
  'MTV Stuttgart': img156,
  Northwestern: img157,
  Wuppertal: img158,
  Wolfenbüttel: img159,
  Kornwestheim: img160,

};

export default teamImageMappings;
